### ISSUE TITLE
Code available?

### ISSUE THREAD

**Issue by syats** [sheryc/QEN#1]
Hi, 
After reading your very interesting paper "QEN: Applicable Taxonomy Completion via Evaluating Full Taxonomic Relations" presented at TheWebConf, I came here looking for the code. Is there any timeplan for this to be uploaded?

Thanks for any info.

**Comment by sheryc** [comment]
Hi,

Thanks for your interest in our work! We are still organizing the code and everything will be released before this Sunday.
